version: '3.8'

services:
  backend:
    image: payment-gateway-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=payment-gateway
    depends_on:
      - mongo

  frontend:
    image: payment-gateway-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - backend

  mongo:
    image: mongo:4.4.4
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
